# Generated by Django 4.1.3 on 2022-12-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_stripe_charge_id_payment_charge_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='ZAR', max_length=50),
        ),
    ]
